### ISSUE TITLE
Is there a way to run DJs command in each reboot?

### ISSUE THREAD

**Issue by PranavBhattarai** [Magisk-Modules-Repo/djs#3]
I use "Detach" module to detach playstore link of YouTube, so that it doesn't get update automatically because I have installed another module called "YouTube Vanced" which install as YouTube systemlessly.

Also I use "Scheduled power on/off" of phone settings from 1:30Am to 4:45Am. This causes, Detach module to not function properly and YouTube app get updated in playstore. And I have to factory reset the app to use Magisk's YouTube Vanced.

Question: How should I use ur module to apply detach each time I reboot? Regardless of what time it is? Cause we have "DJS" function baised on time, so...!?

(Consider this a feature request, if this is not possible yet.)

![Screenshot_20190426-095451](https://user-images.githubusercontent.com/32763112/56783239-4df5da00-67da-11e9-91a8-c8a2d58a3ef3.jpg)
![Screenshot_20190426-095519](https://user-images.githubusercontent.com/32763112/56783259-6fef5c80-67da-11e9-9c3d-6cb335d6454f.jpg)
![Screenshot_20190426-095610](https://user-images.githubusercontent.com/32763112/56783272-7f6ea580-67da-11e9-951b-2eba9aec2350.jpg)

**Comment by VR-25** [comment]
"Run on boot" (regardless of time) is not supported, but it will be implemented.

**Comment by VR-25** [comment]
Hi,
The latest release can run scripts/commands on boot.
`djs-config --append boot "COMMANDS"` - read the documentation for details.
I can't tell what to run to detach YouTube on boot, as I don't use Detach.
I do use YouTube Vanced - and I simply told Play Store to ignore YouTube updates.
